// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: gossip.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GossipEnvelope is the wire format for gossip exchanges.
// The records field carries opaque serialised payloads — the gossip engine
// does not know or care about record structure. Each consumer (HSTLES LAD,
// Hospitium CRDTs, Mercury announcements) defines its own record proto.
//
// When this package extracts to Whisper, this proto moves with it.
// The LADRecord message below stays in HSTLES/Ledger.
type GossipEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *ExchangeMeta          `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Records       [][]byte               `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"` // opaque serialised records
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipEnvelope) Reset() {
	*x = GossipEnvelope{}
	mi := &file_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipEnvelope) ProtoMessage() {}

func (x *GossipEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipEnvelope.ProtoReflect.Descriptor instead.
func (*GossipEnvelope) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *GossipEnvelope) GetMeta() *ExchangeMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GossipEnvelope) GetRecords() [][]byte {
	if x != nil {
		return x.Records
	}
	return nil
}

// ExchangeMeta carries per-exchange metadata piggybacked on gossip frames.
type ExchangeMeta struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CacheFingerprint   uint64                 `protobuf:"varint,1,opt,name=cache_fingerprint,json=cacheFingerprint,proto3" json:"cache_fingerprint,omitempty"`
	Region             string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	BackpressureSignal bool                   `protobuf:"varint,3,opt,name=backpressure_signal,json=backpressureSignal,proto3" json:"backpressure_signal,omitempty"`
	// PEX entries piggybacked on gossip
	PexEntries []*PEXEntry `protobuf:"bytes,4,rep,name=pex_entries,json=pexEntries,proto3" json:"pex_entries,omitempty"`
	// Connection counts for load balancing
	ConnectionCounts map[string]int32 `protobuf:"bytes,5,rep,name=connection_counts,json=connectionCounts,proto3" json:"connection_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Connection offer for NAT traversal signaling
	Offer         *ConnectionOffer `protobuf:"bytes,6,opt,name=offer,proto3" json:"offer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeMeta) Reset() {
	*x = ExchangeMeta{}
	mi := &file_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeMeta) ProtoMessage() {}

func (x *ExchangeMeta) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeMeta.ProtoReflect.Descriptor instead.
func (*ExchangeMeta) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeMeta) GetCacheFingerprint() uint64 {
	if x != nil {
		return x.CacheFingerprint
	}
	return 0
}

func (x *ExchangeMeta) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ExchangeMeta) GetBackpressureSignal() bool {
	if x != nil {
		return x.BackpressureSignal
	}
	return false
}

func (x *ExchangeMeta) GetPexEntries() []*PEXEntry {
	if x != nil {
		return x.PexEntries
	}
	return nil
}

func (x *ExchangeMeta) GetConnectionCounts() map[string]int32 {
	if x != nil {
		return x.ConnectionCounts
	}
	return nil
}

func (x *ExchangeMeta) GetOffer() *ConnectionOffer {
	if x != nil {
		return x.Offer
	}
	return nil
}

// PEXEntry is a signed peer exchange advertisement.
//
// Receivers prefer same-region peers when picking probe targets;
// without `region` on the wire, every received PEXEntry looks like
// it could be cross-region and the same-region preference cannot
// take effect. Mirrors the lad.Record.Region carried in the body
// for direct LADRecord messages.
type PEXEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addresses     []string               `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,3,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PEXEntry) Reset() {
	*x = PEXEntry{}
	mi := &file_gossip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PEXEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PEXEntry) ProtoMessage() {}

func (x *PEXEntry) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PEXEntry.ProtoReflect.Descriptor instead.
func (*PEXEntry) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{2}
}

func (x *PEXEntry) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PEXEntry) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *PEXEntry) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *PEXEntry) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *PEXEntry) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

// ConnectionOffer signals desire for a direct connection.
type ConnectionOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    string                 `protobuf:"bytes,1,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	ToNodeId      string                 `protobuf:"bytes,2,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`
	Addresses     []string               `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Transport     string                 `protobuf:"bytes,4,opt,name=transport,proto3" json:"transport,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,5,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionOffer) Reset() {
	*x = ConnectionOffer{}
	mi := &file_gossip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionOffer) ProtoMessage() {}

func (x *ConnectionOffer) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionOffer.ProtoReflect.Descriptor instead.
func (*ConnectionOffer) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionOffer) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *ConnectionOffer) GetToNodeId() string {
	if x != nil {
		return x.ToNodeId
	}
	return ""
}

func (x *ConnectionOffer) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *ConnectionOffer) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ConnectionOffer) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *ConnectionOffer) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// LADRecord is the wire format for HSTLES/ORBTR directory records.
// This message stays in HSTLES/Ledger when Whisper is extracted —
// it is NOT part of the gossip engine's generic envelope.
//
// Fields 12-15 are the C1 follow-up additions so receiving peers can
// reconstruct the full lad.Record state from a gossip exchange:
//   - hlc_timestamp: HLC tie-breaker for IBLT reconcile and snapshot
//     manifest HLC; without it, every peer interprets the record at
//     HLC=0 and stale records win on equal lamport clocks.
//   - expires_at_unix: TTL for tombstone pruning; without it the
//     receiver treats every record as never-expires.
//   - author_pubkey: signed-topic enforcement — verifiers need the
//     pubkey alongside the signature.
//   - blob_cid: content-addressed reference for off-record blobs
//     (snapshot manifest payloads).
//
// All four use the existing zero-check pattern from `deleted_at_unix`
// so unset fields round-trip cleanly without surprise default-zero
// effects.
type LADRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Topic           string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NodeId          string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TenantId        string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Body            []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"` // opaque sub-document (roles, reach, member JSON)
	TimestampUnix   int64                  `protobuf:"varint,5,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	LamportClock    uint64                 `protobuf:"varint,6,opt,name=lamport_clock,json=lamportClock,proto3" json:"lamport_clock,omitempty"`
	Seq             uint64                 `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	Tombstone       bool                   `protobuf:"varint,8,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	DeletedAtUnix   int64                  `protobuf:"varint,9,opt,name=deleted_at_unix,json=deletedAtUnix,proto3" json:"deleted_at_unix,omitempty"`
	TombstoneReason string                 `protobuf:"bytes,10,opt,name=tombstone_reason,json=tombstoneReason,proto3" json:"tombstone_reason,omitempty"`
	Signature       []byte                 `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
	HlcTimestamp    uint64                 `protobuf:"varint,12,opt,name=hlc_timestamp,json=hlcTimestamp,proto3" json:"hlc_timestamp,omitempty"`
	ExpiresAtUnix   int64                  `protobuf:"varint,13,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	AuthorPubkey    []byte                 `protobuf:"bytes,14,opt,name=author_pubkey,json=authorPubkey,proto3" json:"author_pubkey,omitempty"`
	BlobCid         string                 `protobuf:"bytes,15,opt,name=blob_cid,json=blobCid,proto3" json:"blob_cid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LADRecord) Reset() {
	*x = LADRecord{}
	mi := &file_gossip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LADRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LADRecord) ProtoMessage() {}

func (x *LADRecord) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LADRecord.ProtoReflect.Descriptor instead.
func (*LADRecord) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{4}
}

func (x *LADRecord) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *LADRecord) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LADRecord) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LADRecord) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *LADRecord) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *LADRecord) GetLamportClock() uint64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

func (x *LADRecord) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LADRecord) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

func (x *LADRecord) GetDeletedAtUnix() int64 {
	if x != nil {
		return x.DeletedAtUnix
	}
	return 0
}

func (x *LADRecord) GetTombstoneReason() string {
	if x != nil {
		return x.TombstoneReason
	}
	return ""
}

func (x *LADRecord) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *LADRecord) GetHlcTimestamp() uint64 {
	if x != nil {
		return x.HlcTimestamp
	}
	return 0
}

func (x *LADRecord) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *LADRecord) GetAuthorPubkey() []byte {
	if x != nil {
		return x.AuthorPubkey
	}
	return nil
}

func (x *LADRecord) GetBlobCid() string {
	if x != nil {
		return x.BlobCid
	}
	return ""
}

var File_gossip_proto protoreflect.FileDescriptor

const file_gossip_proto_rawDesc = "" +
	"\n" +
	"\fgossip.proto\x12\x15hstles.mesh.gossip.v1\"c\n" +
	"\x0eGossipEnvelope\x127\n" +
	"\x04meta\x18\x01 \x01(\v2#.hstles.mesh.gossip.v1.ExchangeMetaR\x04meta\x12\x18\n" +
	"\arecords\x18\x02 \x03(\fR\arecords\"\xb1\x03\n" +
	"\fExchangeMeta\x12+\n" +
	"\x11cache_fingerprint\x18\x01 \x01(\x04R\x10cacheFingerprint\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12/\n" +
	"\x13backpressure_signal\x18\x03 \x01(\bR\x12backpressureSignal\x12@\n" +
	"\vpex_entries\x18\x04 \x03(\v2\x1f.hstles.mesh.gossip.v1.PEXEntryR\n" +
	"pexEntries\x12f\n" +
	"\x11connection_counts\x18\x05 \x03(\v29.hstles.mesh.gossip.v1.ExchangeMeta.ConnectionCountsEntryR\x10connectionCounts\x12<\n" +
	"\x05offer\x18\x06 \x01(\v2&.hstles.mesh.gossip.v1.ConnectionOfferR\x05offer\x1aC\n" +
	"\x15ConnectionCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x9e\x01\n" +
	"\bPEXEntry\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\taddresses\x18\x02 \x03(\tR\taddresses\x12%\n" +
	"\x0etimestamp_unix\x18\x03 \x01(\x03R\rtimestampUnix\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\"\xd2\x01\n" +
	"\x0fConnectionOffer\x12 \n" +
	"\ffrom_node_id\x18\x01 \x01(\tR\n" +
	"fromNodeId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x02 \x01(\tR\btoNodeId\x12\x1c\n" +
	"\taddresses\x18\x03 \x03(\tR\taddresses\x12\x1c\n" +
	"\ttransport\x18\x04 \x01(\tR\ttransport\x12%\n" +
	"\x0etimestamp_unix\x18\x05 \x01(\x03R\rtimestampUnix\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\"\xe5\x03\n" +
	"\tLADRecord\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12%\n" +
	"\x0etimestamp_unix\x18\x05 \x01(\x03R\rtimestampUnix\x12#\n" +
	"\rlamport_clock\x18\x06 \x01(\x04R\flamportClock\x12\x10\n" +
	"\x03seq\x18\a \x01(\x04R\x03seq\x12\x1c\n" +
	"\ttombstone\x18\b \x01(\bR\ttombstone\x12&\n" +
	"\x0fdeleted_at_unix\x18\t \x01(\x03R\rdeletedAtUnix\x12)\n" +
	"\x10tombstone_reason\x18\n" +
	" \x01(\tR\x0ftombstoneReason\x12\x1c\n" +
	"\tsignature\x18\v \x01(\fR\tsignature\x12#\n" +
	"\rhlc_timestamp\x18\f \x01(\x04R\fhlcTimestamp\x12&\n" +
	"\x0fexpires_at_unix\x18\r \x01(\x03R\rexpiresAtUnix\x12#\n" +
	"\rauthor_pubkey\x18\x0e \x01(\fR\fauthorPubkey\x12\x19\n" +
	"\bblob_cid\x18\x0f \x01(\tR\ablobCidB9Z7github.com/hstles/loom/core/directory/gossip/pbb\x06proto3"

var (
	file_gossip_proto_rawDescOnce sync.Once
	file_gossip_proto_rawDescData []byte
)

func file_gossip_proto_rawDescGZIP() []byte {
	file_gossip_proto_rawDescOnce.Do(func() {
		file_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gossip_proto_rawDesc), len(file_gossip_proto_rawDesc)))
	})
	return file_gossip_proto_rawDescData
}

var file_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gossip_proto_goTypes = []any{
	(*GossipEnvelope)(nil),  // 0: hstles.mesh.gossip.v1.GossipEnvelope
	(*ExchangeMeta)(nil),    // 1: hstles.mesh.gossip.v1.ExchangeMeta
	(*PEXEntry)(nil),        // 2: hstles.mesh.gossip.v1.PEXEntry
	(*ConnectionOffer)(nil), // 3: hstles.mesh.gossip.v1.ConnectionOffer
	(*LADRecord)(nil),       // 4: hstles.mesh.gossip.v1.LADRecord
	nil,                     // 5: hstles.mesh.gossip.v1.ExchangeMeta.ConnectionCountsEntry
}
var file_gossip_proto_depIdxs = []int32{
	1, // 0: hstles.mesh.gossip.v1.GossipEnvelope.meta:type_name -> hstles.mesh.gossip.v1.ExchangeMeta
	2, // 1: hstles.mesh.gossip.v1.ExchangeMeta.pex_entries:type_name -> hstles.mesh.gossip.v1.PEXEntry
	5, // 2: hstles.mesh.gossip.v1.ExchangeMeta.connection_counts:type_name -> hstles.mesh.gossip.v1.ExchangeMeta.ConnectionCountsEntry
	3, // 3: hstles.mesh.gossip.v1.ExchangeMeta.offer:type_name -> hstles.mesh.gossip.v1.ConnectionOffer
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gossip_proto_init() }
func file_gossip_proto_init() {
	if File_gossip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gossip_proto_rawDesc), len(file_gossip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gossip_proto_goTypes,
		DependencyIndexes: file_gossip_proto_depIdxs,
		MessageInfos:      file_gossip_proto_msgTypes,
	}.Build()
	File_gossip_proto = out.File
	file_gossip_proto_goTypes = nil
	file_gossip_proto_depIdxs = nil
}
